version: 0.2

phases:
install:
- echo installing NGINX
- sudo apt-get update
- sudo apt-get install nginx -y

build:
commands:
- echo build started on 'date'
- cp index.html /var/www/html/
post build:
commands:
- echo comfiguring nginx


artifacts:
files:
- /var/www/html/index.html